server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

admin.username=admin
admin.password=admin@123
jwt.secret=your-256-bit-secret-key-here-make-it-long-enough
jwt.access-token-expiry=900000
jwt.refresh-token-expiry=86400000

node.notification.url=gandhi-market-price-tracker-whatsapp-service-nlxn3p6es.vercel.app/send-price
