spring.application.name=gandhi-market-price-tracker-api
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/crop_market
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

admin.username=admin
admin.password=admin@123
jwt.secret=your-256-bit-secret-key-here-make-it-long-enough
jwt.access-token-expiry=900000
jwt.refresh-token-expiry=86400000

node.notification.url=gandhi-market-price-tracker-whatsapp-service-nlxn3p6es.vercel.app/send-price

# Mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sivasankarkp88@gmail.com
spring.mail.password=najd lqqn mdah gpjy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Admin email to notify
admin.email=sivasankar8383@gmail.com